#!/bin/bash
if [[ $(whoami) == "root" ]]; then
		exec "$@"
	else
		exec pkexec "$0" "$@"
fi
apt install -y  software-properties-common
cp /etc/apt/sources.list /etc/apt/sources.list.backup
touch /etc/apt/sources.touched

grep  '^deb.*debian/ stretch*main'  /etc/apt/sources.list | while read -r line ; do
    echo "Processing $line"
    apt-add-repository "$line  non-free contrib"

done

grep  '^deb.*stretch.updates.main'  /etc/apt/sources.list | while read -r line ; do
    echo "Processing $line"
    apt-add-repository "$line  non-free contrib"

done


grep  '^deb.http://.*debian/ stretch-updates.*main'  /etc/apt/sources.list | while read -r line ; do
    echo "Processing $line"
    apt-add-repository "$line  non-free contrib"

done



